@host = https://localhost:7239

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNWVhNTQ5Mi0zMWVhLTRkOTUtYmUzMC0xZjhjYjc0NDA0MWMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiNjkyMDZiOGQtNjQ2Yy00ZGZhLWFkM2EtMDcxOGZiM2JmMTNmIiwiZXhwIjoxNjYxNDc3NzI3LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.vikUm4e4qzXp31kjC5n-b09tVms9IfdfZtUH7hVvvng